# 1. Create a 3x3x3 array with random values 

In [10]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6], [7,8,9]]])

b = np.random.random((3,3,3))
print(a)
print(a.ndim)
print(b)
print(b.ndim)



[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
[[[0.17134821 0.7218908  0.76572983]
  [0.5263398  0.6221952  0.04409913]
  [0.91635971 0.11133324 0.21680468]]

 [[0.72213454 0.27595964 0.73236181]
  [0.50283552 0.54790672 0.73591774]
  [0.95669398 0.62860352 0.1275099 ]]

 [[0.29721003 0.23634235 0.65434439]
  [0.79371869 0.37522647 0.93703045]
  [0.00164326 0.96266958 0.98690222]]]
3


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [28]:
import numpy as np
x = np.zeros((5,5))
x += np.arange(1,6)
x


array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [40]:
import numpy as np
# x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [41]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.63581414 0.33951159 0.59744849 0.42277435 0.58562145]
 [0.88185558 0.21190813 0.87116005 0.62078352 0.48740828]
 [0.43690832 0.47314474 0.82927947 0.00380077 0.69548457]
 [0.03530483 0.50632045 0.34013832 0.62147014 0.35179802]
 [0.50655523 0.3266328  0.74089171 0.89584156 0.44594752]]
After normalization:
[[0.70850277 0.37634021 0.66549391 0.46967985 0.65223551]
 [0.98432136 0.23329355 0.97233141 0.69165307 0.54213609]
 [0.48552438 0.52614631 0.92538223 0.         0.77539481]
 [0.03531685 0.5633371  0.37704279 0.69242278 0.39011361]
 [0.5636003  0.36190277 0.82629735 1.         0.49565755]]


# 5.  How to find common values between two arrays?

In [42]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [43]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [45]:
import numpy as np
x = np.random.randint(0,2,10)
print("First array:")
print(x)
y = np.random.randint(0,2,10)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 0 0 1 1 1 1 1 1 0]
Second array:
[1 1 1 1 1 1 1 0 1 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [46]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.18157711 0.24763711 0.70921643 0.77001281 0.86401521 0.01660489
 0.00649655 0.82047076 0.4955623  0.53217432]
Maximum value replaced by 0:
[0.18157711 0.24763711 0.70921643 0.77001281 0.         0.01660489
 0.00649655 0.82047076 0.4955623  0.53217432]


# 9. How to print all the values of an array?

In [49]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)

# 10.Subtract the mean of each row of a matrix

In [50]:
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.03472258 0.75941306 0.78152797 0.24170082 0.10604569 0.87795752
  0.07784155 0.89155364 0.59417648 0.72065223]
 [0.90935181 0.8528051  0.74186145 0.96309669 0.22638414 0.73953222
  0.73940262 0.320741   0.89706709 0.17699585]
 [0.59143159 0.45292442 0.46764469 0.10170469 0.52148231 0.15025002
  0.32642446 0.09274056 0.88253166 0.07692713]
 [0.66234617 0.74636795 0.18159069 0.42466126 0.61262139 0.45193331
  0.34372627 0.39880329 0.37057741 0.06833841]
 [0.17688785 0.02125029 0.46028921 0.2431743  0.23147426 0.39470167
  0.70916928 0.89165361 0.54423866 0.11517983]]

Subtract the mean of each row of the said matrix:

[[-0.47383657  0.25085391  0.27296882 -0.26685834 -0.40251346  0.36939836
  -0.43071761  0.38299449  0.08561732  0.21209308]
 [ 0.25262801  0.1960813   0.08513765  0.30637289 -0.43033966  0.08280843
   0.08267882 -0.3359828   0.2403433  -0.47972795]
 [ 0.22502544  0.08651827  0.10123854 -0.26470146  0.15507616 -0.21615613
  -0.0399817  -0.27366559  0.5

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [103]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)


Z += np.bincount(I, minlength=len(Z))

print(Z)

[1. 1. 4. 2. 6. 4. 4. 3. 4. 1.]


# 12.How to get the diagonal of a dot product?

In [104]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
c = np.dot(a, b)
print(c)
d = np.diag(c)
d

[[4 1]
 [2 2]]


array([4, 2])

# 13.How to find the most frequent value in an array?

In [105]:
a = np.array([1,2,3,4,2,2,2,1,4])
np.median(a)

2.0

# 14.How to get the n largest values of an array

In [106]:
import numpy as np
x = np.arange(10)
print("Original array:")

np.random.shuffle(x)

n = int(input('Enter the nth largest number youn want to find: '))
print (x[np.argsort(x)[-n:]][0])





Original array:
Enter the nth largest number youn want to find: 2
8


# 15.How to create a record array from a regular array?

In [77]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
